DROP TABLE IF EXISTS codes CASCADE;
CREATE TABLE IF NOT EXISTS codes (
    id SERIAL PRIMARY KEY,
    code TEXT NOT NULL,
    user_id INT NOT NULL UNIQUE,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);